---
- hosts: all
  become: true
  pre_tasks:

    - name: Update Repository Index (Ubuntu and CentOS)
      package:
        update_cache: yes
      changed_when: false

- hosts: all
  become: true
  vars:
    github_repo_url: https://github.com/ideateGudy/shopping-list.git
    destination_path: /var/www/html
  roles:
    - apache
    - git


